#!/usr/bin/bash

PREFIX=django-
DJANGO_VERSION=1.6.5
PYTHON_VERSION=2.7

AUTHOR_NAME=$(git config user.name)
AUTHOR_EMAIL=$(git config user.email)

if [ $# -eq 0 ]; then
	echo "[ERROR] No name specified"
	exit 1
fi

NAME=$1
SAFE_NAME="${NAME//-/_}"
FULL_NAME=$PREFIX$NAME

URL="https://pypi.python.org/pypi/$FULL_NAME"

YEAR=$(date +"%Y")

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
APPDIR=$(pwd)

cd $DIR
	rm -f app_template.zip
	zip -r app_template.zip app_template

	rm -f project_template.zip
	zip -r project_template.zip project_template
cd $APPDIR

mkdir $FULL_NAME

cd $FULL_NAME

	django-admin startapp --template="$DIR/app_template.zip" $SAFE_NAME

	sed 's/{{ SAFE_NAME }}/'"$SAFE_NAME"'/' "$DIR/resources/MANIFEST.in" > MANIFEST.in
	sed 's/{{ FULL_NAME }}/'"$FULL_NAME"'/' "$DIR/resources/README.rst" > README.rst
	sed -i 's/{{ NAME }}/'"$SAFE_NAME"'/' README.rst
	sed 's/{{ YEAR }}/'"$YEAR"'/' "$DIR/resources/LICENSE" > LICENSE
	sed -i 's/{{ AUTHOR_NAME }}/'"$AUTHOR_NAME"'/' LICENSE

	sed 's/{{ NAME }}/'"$NAME"'/' "$DIR/resources/setup.py" > setup.py
	sed -i 's/{{ SAFE_NAME }}/'"$SAFE_NAME"'/' setup.py
	sed -i 's/{{ DJANGO_VERSION }}/'"$DJANGO_VERSION"'/' setup.py
	sed -i 's/{{ AUTHOR_NAME }}/'"$AUTHOR_NAME"'/' setup.py
	sed -i 's/{{ AUTHOR_EMAIL }}/'"$AUTHOR_EMAIL"'/' setup.py
	sed -i 's|{{ URL }}|'"$URL"'|' setup.py

	django-admin startproject --template="$DIR/project_template.zip" demo
	cd demo
		sed -i 's/{{ DJANGO_VERSION }}/'"$DJANGO_VERSION"'/' requirements.txt
		sed -i 's/{{ PYTHON_VERSION }}/'"$PYTHON_VERSION"'/' makefile
		sed -i 's/||APP_NAME||/'"$SAFE_NAME"'/' makefile
		cd demo
			sed -i 's/||APP_NAME||/'"$SAFE_NAME"'/' settings.py
		cd ..
		cd virtualenv
			virtualenv demo
		cd ..
		make install
	cd ..
	
	cp "$DIR/resources/makefile" makefile
	cp "$DIR/resources/gitignore" .gitignore
	cp "$DIR/resources/todo.txt" todo.txt

	git init
	git add -A
	git commit -m "Initial commit"
	git checkout -b development

cd ..

